services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: python TMKv2/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - db
    hostname: webservice
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  debug:
    build: 
      dockerfile: dockerfilecron

      
volumes:
  db-data: