services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: python TMKv2/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
